name: initialize
version: 0.2.0
author: Polymer.dart Authors <web@dartlang.org>
description: Generic building blocks for doing static initialization.
homepage: https://github.com/dart-lang/initialize
dependencies:
  barback: '>=0.14.2 <0.16.0'
  code_transformers: '>=0.2.3 <0.3.0'
  html5lib: '>=0.12.0 <0.13.0'
  path: '>=1.3.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
environment:
  sdk: '>=1.4.0 <2.0.0'
transformers:
- initialize/build/loader_replacer:
    $include: lib/initialize.dart
- initialize:
    $include: test/initializer_test.dart
    entry_point: test/initializer_test.dart
- initialize:
    $include: test/initializer_cycle_error_test.dart
    entry_point: test/initializer_cycle_error_test.dart
- initialize:
    $include: test/initializer_custom_filter_test.dart
    entry_point: test/initializer_custom_filter_test.dart
- initialize:
    $include: test/initializer_type_filter_test.dart
    entry_point: test/initializer_type_filter_test.dart
- initialize:
    $include: test/init_method_test.dart
    entry_point: test/init_method_test.dart
- $dart2js:
    $exclude: '**/*.dart'
